apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-nginx-deployment
  labels:
    app: php-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-nginx
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
        - name: php-fpm
          image: php:8.3-fpm
          ports:
            - containerPort: 9000
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 443
